### ISSUE TITLE
Add to pypi for pip installation

### ISSUE THREAD

**Issue by Stedders** [synek/git-plan#39]

**Comment by Stedders** [comment]
My preference is to use [poetry](https://python-poetry.org/), which combines dependency management and pypi publishing.

We would end up with a single `pyproject.toml` file containing all project settings, we can also merge the tox settings as well.

**Comment by Stedders** [comment]
Any objections or would you prefer a different approach?

**Comment by synek** [comment]
I started with poetry but I ran into trouble and dropped it. I can't remember what the problem was though. Happy to try it again, so feel free to open a PR for it.

One question though, will it be possible to copy files to new filesystem locations as part of the pip installation? It [looks like](https://stackoverflow.com/questions/59802468/post-install-script-with-python-poetry) poetry doesn't support custom installation scripts, whereas with `setup.py` we can add custom functionality to copy files.

Currently, we need to copy `assets/share/*` over to `.local/share/git-plan` and `scripts/git-plan` to `.local/bin/`.
